apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: podinfo
 namespace: flux-system
spec:
 interval: 30s
 ref:
 branch: master
 url: https://github.com/stefanprodan/podinfo
 ref:
   tag: 6.6.0  # Using a specific tag instead of branch
